### ISSUE TITLE
Add description bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#154] opened 2012-12-07 21:53 UTC
I added a description to my broccoli salad.  After I pressed save, the time stayed the same but the time for the photo of my breakfast yogurt changed as well, making the broccoli first when it should be second.  And the time of the yogurt is now incorrect.

http://screencast.com/t/i0YCt9GxTI

**Comment by jdaudier** [comment] 2012-12-08 04:33
Someone left me a comment.  Not sure if this affected anything but my broccoli salad moved again: http://screencast.com/t/0KT0uXrh

**Comment by loicginoux** [comment] 2012-12-12 12:35
from the tests I did, this should be fixed, can you confirm?

**Comment by loicginoux** [comment] 2012-12-12 12:36
this is duplicate of #151. I close this one.

**Closed as completed by loicginoux** 2012-12-12 12:36 UTC
Labels: bug, sprint 6, HIGH PRIORITY
