### ISSUE TITLE
Photos disappearing

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#141] opened 2012-12-05 06:18 UTC
All of my food photos disappeared from Sunday, 12/2 when I uploaded a new pic for today.  

Other beta testers such as vixydish and kspillma experienced the same thing.

**Comment by loicginoux** [comment] 2012-12-06 15:34
Can you tell me a bit more? do you know which photo in particular? can you find it in the admin panel?

**Comment by jdaudier** [comment] 2012-12-06 17:55
if you take a look at my photos from Sunday, they're all gone for somereason

**Comment by loicginoux** [comment] 2012-12-12 12:55
this is a duplicate of #157. I close this one

**Closed as completed by loicginoux** 2012-12-12 12:55 UTC
Labels: bug, sprint 6, HIGH PRIORITY
