### ISSUE TITLE
Safari on iPhone 5

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#206] opened 2013-01-04 08:10 UTC
Do you have a way to get access to an iPhone 5?

Sho had problems signing up using his iPhone 5 (Safari) this afternoon.  

I ended up signing him up using my Mac.

**Comment by loicginoux** [comment] 2013-01-04 13:15
I wil try using the 4s

**Comment by loicginoux** [comment] 2013-01-04 13:39
I manage to sign up in Safari. I am not sure to understand everything but This is what I can tell:
I don't think this is due to his iphone. There is something with Facebook, When he authenticated using facebook. The authentication object got created but the system didn't associated it to the user.
I will try to replicate that...
For now I associated his facebook account with his user account

**Comment by loicginoux** [comment] 2013-01-07 19:02
duplicate of #188 
closing this one

**Closed as completed by loicginoux** 2013-01-07 19:02 UTC
Labels: bug, sprint 6, MEDIUM PRIORITY
