### ISSUE TITLE
Email bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#352] opened 2013-05-26 17:16 UTC
My streak is off 'cuz it says I posted all 7 days but my streak only says 6.  

And yesterday I posted photos but it says I have 0 points. (see email for details)

**Comment by jdaudier** [comment] 2013-05-28 00:01
A new email bug to add to the above:

It says I posted 2 days out of 7, but it should say 1 day out of 7.

![2013-05-27_1658](https://f.cloud.github.com/assets/1666031/570084/89a1bbbc-c729-11e2-8284-340a6e9af78c.png)

**Comment by jdaudier** [comment] 2013-05-28 15:58
Same errors for today's email (May 28)
![2013-05-28_0856](https://f.cloud.github.com/assets/1666031/573382/6649ae64-c7af-11e2-9178-c29124747b76.png)

**Comment by loicginoux** [comment] 2013-05-29 14:31
There were 2 bugs here:
- the progress bar adding the sunday (and counting 3 out of 7 days). This was a a timezone issue, this should be fixed for tomorrow.
- The points showing 0. This is because the points were added only when uploaded from the app but not when sent from the phone. I corrected that as well.

The streak showing "6" is not a bug in my opinion. Since we put this ni place, you just haven't stopped creating photos for a day, so it just accumulates, it will go back to 0 is one day you don't create a photo. 

These change will be pushed in few minutes. You should see changes on tomorrow's email

**Comment by jdaudier** [comment] 2013-05-29 20:13
I feel like I've had a streak of more than 6 days though.

And it shouldn't add Saturday, correct?  You put Sun in your 1st bullet.

**Comment by jdaudier** [comment] 2013-05-30 00:24
I've posted more than 6 days in a row bur streak is stuck on 6.

**Comment by loicginoux** [comment] 2013-05-30 09:05
Sorry it shouldn't add SATURDAY.
I think 6 days ago correspond to the date were I started deploying the new email and streaks. If you are everyday at 6 days streak, that's an issue. Let me know if it doesn't increment on next days.

**Comment by jdaudier** [comment] 2013-05-30 13:43
I've been at streak "6" for the last several days even though I posted photos.

**Comment by loicginoux** [comment] 2013-05-31 09:47
Ok I found and corrected the bug. It should increment normally now, so you should be at 7 on next email.

**Comment by loicginoux** [comment] 2013-06-04 08:40
Have you noticed an error on emails in the last few days?

**Comment by jdaudier** [comment] 2013-06-04 08:53
seems ok so far

**Comment by loicginoux** [comment] 2013-06-04 08:59
I close it. Reopen if you have the issue again.

**Closed as completed by loicginoux** 2013-06-04 08:59 UTC
Labels: bug, HIGH PRIORITY
