### ISSUE TITLE
Updating calories changes the time

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#138] opened 2012-12-04 17:06 UTC
I took a photo of an apple with 0 calories.  It showed up on the site.  I went to the photo to add calories.  Once I hit save, the photo's time changed 8 hours back.  From around 9 am to around 1 am.

I think this should be fixed right away because if someone took a photo early in the day, it might move to a previous day and make it a pain to manually adjust.  Do you agree?

**Comment by loicginoux** [comment] 2012-12-04 20:13
yes looking at it now

**Comment by jdaudier** [comment] 2012-12-05 00:02
Photos are now moving around randomly.  Apple photo was this morning but I just checked and it's now yesterday.  Sunday photos are missing: http://screencast.com/t/quJcDAu3

We should fix this bug ASAP.  Do you agree?

**Comment by loicginoux** [comment] 2012-12-05 08:04
I updated the timezone bug yesterday, this must have changed time to everything.
Can you do a test for me:
- upload a picture. If you don;t change the time It should set the current time in your timezone.
- check on the calendar that it's correctly displayed at the right day and right time.
- click it to open the view box, date and time should be the same
- click edit button, date and time should be the same.

This is quite difficult to test as I am just on the timezone UTC (which is the one used by the system.)
Images have changed day because they were dispalyed and using the time from UTC timezone, so some picture even if they appear for today (UTC timezone) were actually from yesterday  (your timezone)

**Comment by jdaudier** [comment] 2012-12-05 08:47
My photo won't upload.  It's stuck at the progress bar like this: http://screencast.com/t/HduTze3LzowP

**Comment by loicginoux** [comment] 2012-12-05 09:17
Are you still stuck to upload? It's working for me, and it looks like you uploaded few photos looking at the admin panel

**Comment by jdaudier** [comment] 2012-12-05 09:36
I see the photos now.  But when I try to upload, I'm stuck at the progress bar.

**Comment by jdaudier** [comment] 2012-12-05 09:55
Still stuck at progress bar.  Photo time and date is correct but it's not showing under the right day.  It's showing up under yesterday.

**Comment by jdaudier** [comment] 2012-12-05 10:18
Should we roll back to the version before the bug and start over?

**Comment by loicginoux** [comment] 2012-12-05 16:32
Hi Joanne, I would prefer to fix the bug now rather than rolling back to before.
I will try to see what's going on... maybe doing a test with your account if I can't see the bug with mine  (I will then delete the photo I am uploading in your account)

**Comment by loicginoux** [comment] 2012-12-06 15:34
can we close this one?

**Comment by jdaudier** [comment] 2012-12-06 17:26
Still having this bug.  I just updated calories and added description to this photo I took around 9pm or so last night and now the time changed to morning time.  http://screencast.com/t/XKQWD4ud

**Comment by jdaudier** [comment] 2012-12-06 17:29
I just updated the calories on the larabar I ate yesterday and it moved to a different day completely!  what's going on here? =)
http://screencast.com/t/iW0Y8SfY

**Comment by loicginoux** [comment] 2012-12-12 13:08
closing this one as it is a duplicate of #151

**Closed as completed by loicginoux** 2012-12-12 13:08 UTC
Labels: bug, sprint 6, HIGH PRIORITY
