### ISSUE TITLE
Time ago bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#289] opened 2013-03-09 05:39 UTC
http://www.foodrubix.com/data_points/4181

There appears to be a bug with the Feed's "about XX hours ago" feature.  Right now it's 9:37pm. Kim's photo was uploaded around 13 hours ago (8:40 am), but it says 21 hours ago.

![2013-03-08_2136](https://f.cloud.github.com/assets/1666031/239301/918fec5a-887b-11e2-8269-01d170e746f8.png)

**Comment by loicginoux** [comment] 2013-03-15 10:59
duplicate of #279.

**Closed as completed by loicginoux** 2013-03-15 10:59 UTC
Labels: bug, MEDIUM PRIORITY
