### ISSUE TITLE
Drag & drop bug?

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#212] opened 2013-01-06 22:54 UTC
A user have reported a bug using CrowdIntelligence from your website FoodRubix

User's name: Sho

Users e-mail: sho@shomasuicorp.com

Request received: 1/6/2013 11:51:39 PM

Message from Sho:

click drag pictures

click-drag doesn't work across weeks. I have pictures on Sunday that I want to put into Saturday of the previous week.

**Comment by jdaudier** [comment] 2013-01-06 23:32
He was trying to take pictures from today (Sun) and dragging it to yesterday (Sat).  Maybe that's not possible.

**Comment by loicginoux** [comment] 2013-01-07 15:26
no it's not yet implemented. I close this issue as this is not a bug. I created the issue #217 for this feature in future sprints.

**Closed as completed by loicginoux** 2013-01-07 15:26 UTC
Labels: bug, sprint 6, MEDIUM PRIORITY
