### ISSUE TITLE
Payment Options

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#68] opened 2012-10-24 07:39 UTC
After people try it out for 30 days, i'd like to charge them a small fee like $8/mon and $5/mon (if they used the web app for 30 days straight)... meaning we can reimburse them if they are active users.

Another option is to ask them how much they're willing to pay and charge them that amount. http://scratchpad.co said they did this via a pretty simple setup.  They are just using https://stripe.com for payments and integrating it into their own code.

**Comment by loicginoux** [comment] 2012-10-24 07:51
I think this might take a whole sprint for itself... I will estimate that after sprint 5

**Comment by jdaudier** [comment] 2012-10-25 18:55
Andrew Draper / Founder
http://scratchpad.co 

He said:
Every link you got was connected to your email address, so when the survey was submitted the amount you'd said in it was saved so when you went to the payment form it pulled the amount you'd specified.

**Comment by jdaudier** [comment] 2012-11-02 09:33
I used this cool tool and now we can accept payments if we link to this: https://spb.io/s/5wH7xB0ciP

**Comment by jdaudier** [comment] 2012-11-18 22:21
Should we move this to sprint 6?

**Comment by loicginoux** [comment] 2012-11-20 17:03
I think sprint 6 is already quite busy... I would leave it in sprint 7. if you want it in 6, then i need to move issues from 6 to 7

**Comment by jdaudier** [comment] 2012-11-20 19:38
Can we swap this with another issue in sprint 6?  The reason being I think a lot of people try to lose weight on New Year's, so it would be cool if this is ready by Feb 1 (with Jan as the 30 free trial month).

**Comment by loicginoux** [comment] 2012-11-21 10:23
Ok you just need to remove the features that you don;t want in sprint 6.

**Comment by jdaudier** [comment] 2012-11-21 10:31
ok done.  let me know if i need to remove more for sprint 6

**Comment by loicginoux** [comment] 2012-12-01 11:59
this is a duplicate of the new issue #114. I close it

**Closed as completed by loicginoux** 2012-12-01 11:59 UTC
Labels: sprint 6
