### ISSUE TITLE
Repeat photos sent from phone

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#162] opened 2012-12-14 05:33 UTC
When I sent photos from my phone today, I'm getting repeat photos.

http://screencast.com/t/WFWOmtfXC

Annick and Chrissy have the same bug: http://www.foodrubix.com/tremblaa

Annick says: I send a picture from my phone tonight once but it was upload on the web site 5 time.

Actually, if you take a look of all the beta testers, maybe of them have this bug.

**Comment by jdaudier** [comment] 2012-12-14 07:03
We need to fix this ASAP.  The repeat photos are growing!  Yikes!

**Comment by loicginoux** [comment] 2012-12-14 18:01
Mailgun is trying to send emails to the app and receive a 404 error from the app. Mailgun will try a certain amount of times for each email and then stop... I deleted all duplicates and I am now looking into why the app doesn't accept mailgun mails

**Comment by jdaudier** [comment] 2012-12-14 18:02
Do you know why the photos were growing every couple of hours?

**Comment by loicginoux** [comment] 2012-12-14 18:26
I know where is the problem, this bug should have come up before because I didn't change anything. the problem is that the code in the app to process the mail had an error. the image were still created but it was sending an error back to mailgun. Mailgun was interpreting this as a failure so it was trying and trying and trying agin to send the same email.
see mailgun logs:
http://awesomescreenshot.com/055pt6jb0

**Comment by loicginoux** [comment] 2012-12-14 18:31
ok this is working now. What I don't undestand is why mailgun hasn't had this behaviour before and it just started that today...

**Comment by jdaudier** [comment] 2012-12-14 18:33
Didn't we change something on how often we ping the site to see when to send the emails at 2am?  Does it have to do with that?

**Comment by loicginoux** [comment] 2012-12-14 18:40
no

**Comment by loicginoux** [comment] 2012-12-16 16:01
can we close this?

**Closed as completed** 2012-12-16 19:03 UTC
Labels: bug, sprint 6, HIGH PRIORITY
