### ISSUE TITLE
Adding description changes the date of the photo

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#122] opened 2012-12-03 00:13 UTC
I just took a photo of a sandwich earlier.  I tried to add a description.  The photo jumped back to yesterday (dec 1).

I tried to update the date to today and pressed save.  No changes.

I tried to update the date to today the 2nd time.  It updated.

**Comment by loicginoux** [comment] 2012-12-03 11:32
Ok so from the logs, this is something due to timezone. at one point you updated and it updated with the same time but in time zone UTC, so for your time it was the day before...
a bit complicated and I need to do more tests about this timezone thing...
basically there must be a line in the code where I forgot to use the time with timezone.

**Comment by jdaudier** [comment] 2012-12-03 16:40
OK - let's try to fix this soon if you can.  Thanks!

**Comment by jdaudier** [comment] 2012-12-03 16:41
The photo also didn't show up in my daily email

**Comment by jdaudier** [comment] 2012-12-03 21:14
We need to get this fixed ASAP.  Vicky said:

I think there's a bug whenever I "Edit" a photo.  It keeps reverting back to one day earlier so for example, if I edit one of today's photos, it would make it part of yesterday's meal.  I then would need to go back in and reset the date.

**Comment by loicginoux** [comment] 2012-12-06 15:37
This can be closed right? this was the timezone issue

**Comment by jdaudier** [comment] 2012-12-06 17:52
Still a bug.  I just added a description for my cobb salad.  It moved it from 4:46pm to 4:46am the previous day.  Can we fix this ASAP?  Thanks!
http://screencast.com/t/az93luuG12

**Comment by loicginoux** [comment] 2012-12-06 18:41
this was a bug in the library for the timePicker. it wasn't getting the pm value.
(https://github.com/jonthornton/jquery-timepicker/issues/57)

**Comment by jdaudier** [comment] 2012-12-06 19:59
I see... does this mean we have to wait for them to fix the bug?

**Comment by loicginoux** [comment] 2012-12-06 21:20
no no I fixed it directly in our app

**Comment by loicginoux** [comment] 2012-12-12 12:58
this is a duplicate of #151. I close this one

**Closed as completed by loicginoux** 2012-12-12 12:58 UTC
Labels: bug, sprint 6, HIGH PRIORITY
